defaults: &defaults
  working_directory: ~/repo

jobs:
  one:
    docker:
      - image: circleci/node:8.9.1 
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install  #install node.js package
      - run:
          name: Run tests
          command: npm test
  two:
    orbs:
      heroku: circleci/heroku@1.0.0
    deploy: 
      executor: heroku/default
      steps:
        - checkout
        - heroku/install
        - heroku/deploy-via-git
      ignore: master
      deploy-via-git:
        parameters:
          app-name:
            type: string
            default: $tnkotsu-vishwasnm2-staging
          api-key:
            type: string
            default: $71ab5865-2164-41b3-868c-bf48f1c8e7ec

workflows:
  version: 2
  only_test:
    jobs:
      - one
      - two
